[tool.black]
line-length = 79           # Longueur choisie selon PEP8 (79 caractères)
target-version = ['py311'] # À adapter à ta version Python
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true

[tool.ruff]
line-length = 79
select = ["E", "F", "W"]  # Active les règles d’erreur, de warning, etc. (flakey, style, etc.)
ignore = []
exclude = [
    "build",
    "dist",
    ".venv",
    ".git",
]

[tool.pyright]
typeCheckingMode = "basic"           # Peut être "off", "basic", ou "strict"
pythonVersion = "3.11"
pythonPlatform = "Linux"
include = ["src"]                    # Dossier(s) à analyser, ajuste selon la structure de ton projet
exclude = ["**/tests/**", ".venv"]   # Dossiers à exclure de l’analyse
reportMissingTypeStubs = true        # Signaler les stubs manquants
reportUnusedImport = true            # Remonter les imports inutilisés
